---
title: "Microbial Sequencing of Flies"
---

A fly's microbiota can be sequenced using several approaches, including:

-   Short-read 16S rRNA sequencing

-   Long-read 16S rRNA sequencing

-   Shotgun metagenomic sequencing

**Short-read 16S rRNA sequencing**:

-    Targets and sequences short variable regions of the 16S rRNA gene (e.g., V3--V4) -

-   Uses sequencing platforms such as Illumina. - It provides high-throughput, cost-effective profiling of bacterial community composition but limited taxonomic resolution, often to the genus level.

**Long-read 16S rRNA sequencing**:

-    Sequences the full-length 16S rRNA gene using technologies like Oxford Nanopore or PacBio.

-   This approach improves taxonomic resolution, often enabling species- or even strain-level identification, though with higher cost and potential sequencing error rates.

-   A problem with some Medfly papers is that despite use of long-read sequencing, some results only show to the genus level, this is due to a lack of update in taxonomic classifiers.

**Shotgun metagenomic sequencing**:

-    Sequences all genomic DNA present in a sample, not just the 16S rRNA gene.

-    It allows for comprehensive profiling of microbial diversity (including bacteria, archaea, fungi, and viruses) and provides insights into functional gene content, metabolic pathways, and strain-level variation.





**Sequencing of the Medfly gut microbiota**: 

      
- The majority of Medfly sequencing studies use short-read 16S, there are only a few to have used long read sequencing. 
- This year, Mason et al. 2025 have published two studies that have sequenced the Medfly microbiota, however their results only go to the genus level. 
- There have been no studies in Medfly, or even Tephritids, to have used metagenomics.
- We plan to do a pilot metagenomic study: with a small sample size to establish if we get any microbial DNA, or to see if Medfly DNA overrides this.



