---
title: "Tephritid Microbe Functions"
editor: visual
---

## Why do we care about the Tephritid microbiota?

- Tephritid flies host specialized microbial partners that play vital roles in their physiology and ecology.  
- These symbionts contribute to nutrient acquisition, digestion, and development—helping their hosts thrive across a range of environments.     
    
Below are key examples of functionally important microbial associations identified in major Tephritid species:

::: {.columns}
::: {.column width="33%"}
#### *Bactrocera oleae*
- Nitrogen metabolism  
- Obligate symbiont *Ca. Erwinia dacicola*  
- Accelerated larval development  
([Campos et al., 2022](https://www.frontiersin.org/articles/10.3389/fmicb.2022.868458/full))
:::

::: {.column width="33%"}
#### *Ceratitis capitata*
- Enhanced development and longevity  
- Carbon and nitrogen metabolism  
- Suppression of pathogenic *Pseudomonas*  
([Behar et al., 2008](https://doi.org/10.1017/S0020751008003217))
:::

::: {.column width="33%"}
#### *Rhagoletis pomonella*
- Facultative symbiosis with *Enterobacter* and *Klebsiella*  
- Purine degradation  
- Nitrogen provisioning  
([Ren et al., 2022](https://www.mdpi.com/2075-4450/13/1/84))
:::
:::

## SIT × Microbiota

- The **Sterile Insect Technique (SIT)** is a powerful, environmentally friendly method for pest control that relies on the mass release of sterilised males to suppress wild populations through infertile matings.  
- However, irradiation and mass-rearing conditions can disrupt the natural gut microbiota of flies—potentially reducing male fitness, competitiveness, and lifespan.

- Microbiota restoration through probitoics could enhance SIT effectiveness.
- By supplementing or reintroducing beneficial bacteria (e.g., *Klebsiella*, *Enterobacter*, or genera of the Enterobacteriacae family), it may be possible to:

- Improve sterile male mating competitiveness  
- Increase survival and flight ability post-irradiation  
- Support nutrient assimilation and energy metabolism during stress  
- Reduce handling stress and mortality during release  


This shows the importance of **“SIT × Microbiota”** in using the microbiota for pest management; optimising the sterile insect performance. 


